package asandrc.gmail.com.view;

import asandrc.gmail.com.data.FAT32DIRElement;
import asandrc.gmail.com.data.FAT32Directory;
import asandrc.gmail.com.extractor.FAT32Extractor;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.ListModel;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Саша
 */
public class MainFrame extends javax.swing.JFrame {

    private FAT32Extractor fat32Extractor;

    public void setFat32Extractor(FAT32Extractor fat32Extractor) {
        this.fat32Extractor = fat32Extractor;
    }
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        fat32Extractor = new FAT32Extractor();
        jTree = new JTree();
        jTree.setModel(null);
        contentList = new JList();
        jScrollPane1.setViewportView(jTree);
    }
    
    private void getInfo() {
        infoTextArea.setText("");
        infoTextArea.append(" Тип FAT: " + fat32Extractor.getTypeOfFileSystem());
        infoTextArea.append("\n BS_OEMNAME: " + fat32Extractor.getBS_OEMNAme());
        infoTextArea.append("\n Байтов в секторе: " + fat32Extractor.getBPB_BytsPerSec().toString());
        infoTextArea.append("\n Секторов в кластере: " + fat32Extractor.getBPB_SecPerClus().toString());
        infoTextArea.append("\n FAT таблиц: " + fat32Extractor.getBPB_NumFATs().toString());
        infoTextArea.append("\n Количество кластеров: " + fat32Extractor.getCountOfClusters().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        contentList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAT32Extractor");
        setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        setName("MainFrame"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Информация о файловой системе", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        infoTextArea.setEditable(false);
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        infoTextArea.setRows(5);
        infoTextArea.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(infoTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Структура FAT раздела", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        jTree.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("dir");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        contentList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Содержимое директории", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N
        contentList.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        contentList.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(contentList);

        jMenuBar1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jMenu1.setText("Файл");
        jMenu1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asandrc/gmail/com/view/resources/icons/package.png"))); // NOI18N
        jMenuItem1.setText("Открыть файл");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asandrc/gmail/com/view/resources/icons/stop.png"))); // NOI18N
        jMenuItem2.setText("Выход");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openFAT();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void openFAT() {
        JFileChooser fileChooser = new JFileChooser("./");
        int answer = fileChooser.showDialog(null, "Октрыть файл FAT");
        if (answer == JFileChooser.APPROVE_OPTION) {
            fat32Extractor.openFAT(fileChooser.getSelectedFile());
            buildTree(fat32Extractor.getRootElement());
            getInfo();
        } else {
            JOptionPane.showMessageDialog(this, "Файл не выбран");
        }
    }
    
    private void buildTree(FAT32Directory rootElement) {
        DefaultMutableTreeNode top = createNodes(rootElement);
        jTree = new JTree(top);
        jTree.getSelectionModel().addTreeSelectionListener(new Selector());
        jScrollPane1.setViewportView(jTree);
    }
    
    private DefaultMutableTreeNode createNodes(FAT32Directory rootElement) {
        DefaultMutableTreeNode node = new DefaultMutableTreeNode(rootElement);
        DefaultMutableTreeNode childNode;
        
        int i = 0;
        FAT32Directory[] childs = new FAT32Directory[rootElement.getChildDirectories().size()];
        for(FAT32Directory child: rootElement.getChildDirectories()) {
            childs[i] = child;
            if (!childs[i].getChildDirectories().isEmpty())
                childNode = createNodes(childs[i]);
            else
                childNode = new DefaultMutableTreeNode(childs[i]);
            node.add(childNode);
            i++;
        }
        return node;
    }
    
    protected void addContentOfDirToList(Object obj) {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) obj;
        FAT32Directory f32Directory = (FAT32Directory) node.getUserObject();
        ListModel listModel = new DefaultListModel();
        contentList = new JList(listModel);
        DefaultListModel model = (DefaultListModel)contentList.getModel();
        for (int i = 0; i < f32Directory.getChildElements().size(); i++) {
            model.addElement(f32Directory.getChildElements().get(i));
        }
        jScrollPane3.setViewportView(contentList);
    }
    
    private class Selector implements TreeSelectionListener {
    public void valueChanged(TreeSelectionEvent event) {
      Object obj = event.getNewLeadSelectionPath().getLastPathComponent();
      addContentOfDirToList(obj);      
    }
  }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList contentList;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
